Return-Path: <linux-fbdev-owner@vger.kernel.org>
X-Original-To: lists+linux-fbdev@lfdr.de
Delivered-To: lists+linux-fbdev@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 26B79132AD8
	for <lists+linux-fbdev@lfdr.de>; Tue,  7 Jan 2020 17:14:07 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1728344AbgAGQOG (ORCPT <rfc822;lists+linux-fbdev@lfdr.de>);
        Tue, 7 Jan 2020 11:14:06 -0500
Received: from mail-wr1-f67.google.com ([209.85.221.67]:33113 "EHLO
        mail-wr1-f67.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1727974AbgAGQOF (ORCPT
        <rfc822;linux-fbdev@vger.kernel.org>); Tue, 7 Jan 2020 11:14:05 -0500
Received: by mail-wr1-f67.google.com with SMTP id b6so42455wrq.0
        for <linux-fbdev@vger.kernel.org>; Tue, 07 Jan 2020 08:14:04 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=ffwll.ch; s=google;
        h=date:from:to:cc:subject:message-id:mail-followup-to:references
         :mime-version:content-disposition:in-reply-to;
        bh=BnDKwUCZGErP+KyVZtLEwU8FgiR2KztEMGDlEQCZd7s=;
        b=it6jWsNZqZnJRkxU0QF0aJRe+H0+HCzalY18g4ewAHrgujNSc8aGGHJOyIkjkmXvPP
         5BXRcjhZEebBC8Fh/fPqNbuvXUVZRTPyF+QlRNp3popqzAHBTYNQLBz/Dzff+SBqtnJb
         i+pZDiEyjvepJxb7O5j423j2fpP6tNpbG9J18=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:date:from:to:cc:subject:message-id
         :mail-followup-to:references:mime-version:content-disposition
         :in-reply-to;
        bh=BnDKwUCZGErP+KyVZtLEwU8FgiR2KztEMGDlEQCZd7s=;
        b=VfHdOg1kXaDoVEwIGp4RdbO2z1ISCl0Mi2aMStF5EoWv+0bq0rVjsnWn2EOIsxDMpE
         Ku1kwR4f6q33+uCRb1/4ULcZ85qQag4KPUu7hKkIB3SqwIYouIv52Elwhfa4wb/m0UOC
         ijOSt2F5ZqVqx9MKl0sDAa5rV2hB8tNw6ZrylZe/yssaofziHIAwavqlyhjZShj/KJNp
         VUvkYw8SUik+/J/4fWepL+BtlwJ3JPITgQT8vxkmrk1PToI/SXpzKnQ2k3qN7smaQQ28
         rXbXFBCSvVP1s2ErB+Z/eDGAiy9N5azZk2YAMxj4bRwEaFUz1RPcWTPxGF5LATKXmLhf
         FLjA==
X-Gm-Message-State: APjAAAXgw4RVEZzTndS1r7IoE1KGZ3JSOKpDUy59oibtgHQunOzV5mfG
        FPmqqVRnwFnW5D39mUxntkkqQw==
X-Google-Smtp-Source: APXvYqyQHK3dzkGnpN+A204ch3gC1JI6BVacIWD7/CNfZ+GZU0DG7Tm8hsvhn35Lq2tPf4RZVD7Biw==
X-Received: by 2002:a5d:4c8c:: with SMTP id z12mr79526820wrs.222.1578413643880;
        Tue, 07 Jan 2020 08:14:03 -0800 (PST)
Received: from phenom.ffwll.local ([2a02:168:564b:0:7567:bb67:3d7f:f863])
        by smtp.gmail.com with ESMTPSA id q14sm133727wmj.14.2020.01.07.08.14.02
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Tue, 07 Jan 2020 08:14:03 -0800 (PST)
Date:   Tue, 7 Jan 2020 17:14:01 +0100
From:   Daniel Vetter <daniel@ffwll.ch>
To:     Julia Lawall <julia.lawall@inria.fr>
Cc:     Bartlomiej Zolnierkiewicz <b.zolnierkie@samsung.com>,
        linux-fbdev@vger.kernel.org, kbuild-all@lists.01.org,
        "Gustavo A. R. Silva" <gustavo@embeddedor.com>,
        linux-kernel@vger.kernel.org, dri-devel@lists.freedesktop.org,
        Steve Winslow <swinslow@gmail.com>,
        Jilayne Lovejoy <opensource@jilayne.com>,
        Thomas Gleixner <tglx@linutronix.de>,
        Allison Randal <allison@lohutok.net>
Subject: Re: [PATCH] video: fbdev: mmp: fix platform_get_irq.cocci warnings
Message-ID: <20200107161401.GF43062@phenom.ffwll.local>
Mail-Followup-To: Julia Lawall <julia.lawall@inria.fr>,
        Bartlomiej Zolnierkiewicz <b.zolnierkie@samsung.com>,
        linux-fbdev@vger.kernel.org, kbuild-all@lists.01.org,
        "Gustavo A. R. Silva" <gustavo@embeddedor.com>,
        linux-kernel@vger.kernel.org, dri-devel@lists.freedesktop.org,
        Steve Winslow <swinslow@gmail.com>,
        Jilayne Lovejoy <opensource@jilayne.com>,
        Thomas Gleixner <tglx@linutronix.de>,
        Allison Randal <allison@lohutok.net>
References: <alpine.DEB.2.21.2001042140310.6944@hadrien>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <alpine.DEB.2.21.2001042140310.6944@hadrien>
X-Operating-System: Linux phenom 5.3.0-3-amd64 
Sender: linux-fbdev-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-fbdev.vger.kernel.org>
X-Mailing-List: linux-fbdev@vger.kernel.org

On Sat, Jan 04, 2020 at 09:43:31PM +0100, Julia Lawall wrote:
> From: kbuild test robot <lkp@intel.com>
> 
> Remove dev_err() messages after platform_get_irq*() failures.
> Line 450 is redundant because platform_get_irq() already prints
> an error.
> 
> Generated by: scripts/coccinelle/api/platform_get_irq.cocci
> 
> Fixes: dd90e9ae55a1 ("video: fbdev: mmp: add COMPILE_TEST support")
> Signed-off-by: kbuild test robot <lkp@intel.com>
> Signed-off-by: Julia Lawall <julia.lawall@inria.fr>

Applied to drm-misc-next, thanks for your patch.
-Daniel

> 
> ---
> 
> tree:   git://anongit.freedesktop.org/drm/drm-misc for-linux-next
> head:   80805774fc354f9ae7755a8e649a01dedfd0dcf8
> commit: dd90e9ae55a1e7efd3ac036afe9f7ae7bb64d39d [2/16] video: fbdev: mmp: add COMPILE_TEST support
> :::::: branch date: 11 hours ago
> :::::: commit date: 11 hours ago
> 
>  mmp_ctrl.c |    1 -
>  1 file changed, 1 deletion(-)
> 
> --- a/drivers/video/fbdev/mmp/hw/mmp_ctrl.c
> +++ b/drivers/video/fbdev/mmp/hw/mmp_ctrl.c
> @@ -447,7 +447,6 @@ static int mmphw_probe(struct platform_d
> 
>  	irq = platform_get_irq(pdev, 0);
>  	if (irq < 0) {
> -		dev_err(&pdev->dev, "%s: no IRQ defined\n", __func__);
>  		ret = -ENOENT;
>  		goto failed;
>  	}
> _______________________________________________
> dri-devel mailing list
> dri-devel@lists.freedesktop.org
> https://lists.freedesktop.org/mailman/listinfo/dri-devel

-- 
Daniel Vetter
Software Engineer, Intel Corporation
http://blog.ffwll.ch
