Return-Path: <linux-fbdev-owner@vger.kernel.org>
X-Original-To: lists+linux-fbdev@lfdr.de
Delivered-To: lists+linux-fbdev@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 5C7F818BB89
	for <lists+linux-fbdev@lfdr.de>; Thu, 19 Mar 2020 16:49:29 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1727521AbgCSPt3 (ORCPT <rfc822;lists+linux-fbdev@lfdr.de>);
        Thu, 19 Mar 2020 11:49:29 -0400
Received: from mx2.suse.de ([195.135.220.15]:53280 "EHLO mx2.suse.de"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S1727265AbgCSPt2 (ORCPT <rfc822;linux-fbdev@vger.kernel.org>);
        Thu, 19 Mar 2020 11:49:28 -0400
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
        by mx2.suse.de (Postfix) with ESMTP id AE04CAC3A;
        Thu, 19 Mar 2020 15:49:27 +0000 (UTC)
Date:   Thu, 19 Mar 2020 16:49:27 +0100
Message-ID: <s5hh7ykuyyg.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Bartlomiej Zolnierkiewicz <b.zolnierkie@samsung.com>
Cc:     linux-fbdev@vger.kernel.org
Subject: Re: [PATCH 0/3] video: Use scnprintf() for avoiding potential buffer overflow
In-Reply-To: <20200311093230.24900-1-tiwai@suse.de>
References: <20200311093230.24900-1-tiwai@suse.de>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-fbdev-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-fbdev.vger.kernel.org>
X-Mailing-List: linux-fbdev@vger.kernel.org

On Wed, 11 Mar 2020 10:32:27 +0100,
Takashi Iwai wrote:
> 
> Hi,
> 
> here is a series of trivial patches just to convert suspicious
> snprintf() usages with the more safer one, scnprintf().
> 
> 
> Takashi
> 
> ===
> 
> Takashi Iwai (3):
>   video: omapfb: Use scnprintf() for avoiding potential buffer overflow
>   video: omap2: Use scnprintf() for avoiding potential buffer overflow
>   video: uvesafb: Use scnprintf() for avoiding potential buffer overflow
> 
>  drivers/video/fbdev/omap/omapfb_main.c          | 14 +++++++-------
>  drivers/video/fbdev/omap2/omapfb/omapfb-sysfs.c |  8 ++++----
>  drivers/video/fbdev/uvesafb.c                   |  2 +-
>  3 files changed, 12 insertions(+), 12 deletions(-)

Just a gentle ping about those patches.
Let me know if any further changes needed.


thanks,

Takashi
